name: Good Fences
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x]

    steps:

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.1.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
            ./node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check fences
        run: pnpm run fences

  delete_github_deployments:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test
    if: ${{ always() }} # run even on error
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete Deploys
        uses: ./.github/workflows/delete-deploy
